// This configuration is automatically generated by Firebase Studio.
// Do not edit this file manually.
export const firebaseConfig = {
  apiKey: "PLACEHOLDER_API_KEY",
  authDomain: "PLACEHOLDER_AUTH_DOMAIN",
  databaseURL: "https://next-js-starter-1e35d-default-rtdb.firebaseio.com",
  projectId: "next-js-starter-1e35d",
  storageBucket: "next-js-starter-1e35d.appspot.com",
  messagingSenderId: "323530722778",
  appId: "1:323530722778:web:7c9d11649340798a68bf26",
  measurementId: "G-J9029L9Z2E",
};
